baseURL = 'https://stonenet.org/'
languageCode = 'en-us'
title = 'Stonenet'
theme = 'risotto'
sectionPagesMenu = 'main'



[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Download'
  url = '/download'
  weight = 2

